// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comm.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Specifies the message type in a peer request and reply
type MsgType int32

const (
	MsgType_PREACCEPT      MsgType = 0
	MsgType_PREACCEPTREPLY MsgType = 1
	MsgType_ACCEPT         MsgType = 2
	MsgType_ACCEPTREPLY    MsgType = 3
	MsgType_COMMIT         MsgType = 4
	MsgType_COMMITREPLY    MsgType = 5
	MsgType_PROPOSE        MsgType = 6
	MsgType_EXITREPLY      MsgType = 8
)

var MsgType_name = map[int32]string{
	0: "PREACCEPT",
	1: "PREACCEPTREPLY",
	2: "ACCEPT",
	3: "ACCEPTREPLY",
	4: "COMMIT",
	5: "COMMITREPLY",
	6: "PROPOSE",
	8: "EXITREPLY",
}

var MsgType_value = map[string]int32{
	"PREACCEPT":      0,
	"PREACCEPTREPLY": 1,
	"ACCEPT":         2,
	"ACCEPTREPLY":    3,
	"COMMIT":         4,
	"COMMITREPLY":    5,
	"PROPOSE":        6,
	"EXITREPLY":      8,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{0}
}

// instance state
type InstState int32

const (
	InstState_PREACCEPTED InstState = 0
	InstState_ACCEPTED    InstState = 2
	InstState_EXECUTED    InstState = 3
)

var InstState_name = map[int32]string{
	0: "PREACCEPTED",
	2: "ACCEPTED",
	3: "EXECUTED",
}

var InstState_value = map[string]int32{
	"PREACCEPTED": 0,
	"ACCEPTED":    2,
	"EXECUTED":    3,
}

func (x InstState) String() string {
	return proto.EnumName(InstState_name, int32(x))
}

func (InstState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{1}
}

// access types from client
type AccessType int32

const (
	AccessType_ACCESS_WRITE     AccessType = 0
	AccessType_ACCESS_READ      AccessType = 1
	AccessType_ACCESS_WRITEREAD AccessType = 2
	AccessType_ACCESS_NULL      AccessType = 3
)

var AccessType_name = map[int32]string{
	0: "ACCESS_WRITE",
	1: "ACCESS_READ",
	2: "ACCESS_WRITEREAD",
	3: "ACCESS_NULL",
}

var AccessType_value = map[string]int32{
	"ACCESS_WRITE":     0,
	"ACCESS_READ":      1,
	"ACCESS_WRITEREAD": 2,
	"ACCESS_NULL":      3,
}

func (x AccessType) String() string {
	return proto.EnumName(AccessType_name, int32(x))
}

func (AccessType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{2}
}

// A wrapper message that can contain one of the request message types.
type PeerRequest struct {
	Type MsgType `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.MsgType" json:"Type,omitempty"`
	From int64   `protobuf:"varint,2,opt,name=From,proto3" json:"From,omitempty"`
	// only one of these fields can be set, and the field that is set should
	// match the message type described above.
	//
	// Types that are valid to be assigned to Message:
	//	*PeerRequest_Preaccept
	//	*PeerRequest_Preacceptreply
	//	*PeerRequest_Accept
	//	*PeerRequest_Acceptreply
	//	*PeerRequest_Commit
	Message              isPeerRequest_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PeerRequest) Reset()         { *m = PeerRequest{} }
func (m *PeerRequest) String() string { return proto.CompactTextString(m) }
func (*PeerRequest) ProtoMessage()    {}
func (*PeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{0}
}

func (m *PeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerRequest.Unmarshal(m, b)
}
func (m *PeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerRequest.Marshal(b, m, deterministic)
}
func (m *PeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerRequest.Merge(m, src)
}
func (m *PeerRequest) XXX_Size() int {
	return xxx_messageInfo_PeerRequest.Size(m)
}
func (m *PeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerRequest proto.InternalMessageInfo

func (m *PeerRequest) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_PREACCEPT
}

func (m *PeerRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

type isPeerRequest_Message interface {
	isPeerRequest_Message()
}

type PeerRequest_Preaccept struct {
	Preaccept *PreacceptRequest `protobuf:"bytes,10,opt,name=preaccept,proto3,oneof"`
}

type PeerRequest_Preacceptreply struct {
	Preacceptreply *PreacceptReply `protobuf:"bytes,11,opt,name=preacceptreply,proto3,oneof"`
}

type PeerRequest_Accept struct {
	Accept *AcceptRequest `protobuf:"bytes,12,opt,name=accept,proto3,oneof"`
}

type PeerRequest_Acceptreply struct {
	Acceptreply *AcceptReply `protobuf:"bytes,13,opt,name=acceptreply,proto3,oneof"`
}

type PeerRequest_Commit struct {
	Commit *CommitRequest `protobuf:"bytes,14,opt,name=commit,proto3,oneof"`
}

func (*PeerRequest_Preaccept) isPeerRequest_Message() {}

func (*PeerRequest_Preacceptreply) isPeerRequest_Message() {}

func (*PeerRequest_Accept) isPeerRequest_Message() {}

func (*PeerRequest_Acceptreply) isPeerRequest_Message() {}

func (*PeerRequest_Commit) isPeerRequest_Message() {}

func (m *PeerRequest) GetMessage() isPeerRequest_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PeerRequest) GetPreaccept() *PreacceptRequest {
	if x, ok := m.GetMessage().(*PeerRequest_Preaccept); ok {
		return x.Preaccept
	}
	return nil
}

func (m *PeerRequest) GetPreacceptreply() *PreacceptReply {
	if x, ok := m.GetMessage().(*PeerRequest_Preacceptreply); ok {
		return x.Preacceptreply
	}
	return nil
}

func (m *PeerRequest) GetAccept() *AcceptRequest {
	if x, ok := m.GetMessage().(*PeerRequest_Accept); ok {
		return x.Accept
	}
	return nil
}

func (m *PeerRequest) GetAcceptreply() *AcceptReply {
	if x, ok := m.GetMessage().(*PeerRequest_Acceptreply); ok {
		return x.Acceptreply
	}
	return nil
}

func (m *PeerRequest) GetCommit() *CommitRequest {
	if x, ok := m.GetMessage().(*PeerRequest_Commit); ok {
		return x.Commit
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PeerRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PeerRequest_OneofMarshaler, _PeerRequest_OneofUnmarshaler, _PeerRequest_OneofSizer, []interface{}{
		(*PeerRequest_Preaccept)(nil),
		(*PeerRequest_Preacceptreply)(nil),
		(*PeerRequest_Accept)(nil),
		(*PeerRequest_Acceptreply)(nil),
		(*PeerRequest_Commit)(nil),
	}
}

func _PeerRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PeerRequest)
	// message
	switch x := m.Message.(type) {
	case *PeerRequest_Preaccept:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Preaccept); err != nil {
			return err
		}
	case *PeerRequest_Preacceptreply:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Preacceptreply); err != nil {
			return err
		}
	case *PeerRequest_Accept:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Accept); err != nil {
			return err
		}
	case *PeerRequest_Acceptreply:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Acceptreply); err != nil {
			return err
		}
	case *PeerRequest_Commit:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Commit); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PeerRequest.Message has unexpected type %T", x)
	}
	return nil
}

func _PeerRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PeerRequest)
	switch tag {
	case 10: // message.preaccept
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreacceptRequest)
		err := b.DecodeMessage(msg)
		m.Message = &PeerRequest_Preaccept{msg}
		return true, err
	case 11: // message.preacceptreply
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreacceptReply)
		err := b.DecodeMessage(msg)
		m.Message = &PeerRequest_Preacceptreply{msg}
		return true, err
	case 12: // message.accept
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AcceptRequest)
		err := b.DecodeMessage(msg)
		m.Message = &PeerRequest_Accept{msg}
		return true, err
	case 13: // message.acceptreply
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AcceptReply)
		err := b.DecodeMessage(msg)
		m.Message = &PeerRequest_Acceptreply{msg}
		return true, err
	case 14: // message.commit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CommitRequest)
		err := b.DecodeMessage(msg)
		m.Message = &PeerRequest_Commit{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PeerRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PeerRequest)
	// message
	switch x := m.Message.(type) {
	case *PeerRequest_Preaccept:
		s := proto.Size(x.Preaccept)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PeerRequest_Preacceptreply:
		s := proto.Size(x.Preacceptreply)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PeerRequest_Accept:
		s := proto.Size(x.Accept)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PeerRequest_Acceptreply:
		s := proto.Size(x.Acceptreply)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PeerRequest_Commit:
		s := proto.Size(x.Commit)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PreacceptRequest struct {
	Inst                 *Instance `protobuf:"bytes,1,opt,name=Inst,proto3" json:"Inst,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PreacceptRequest) Reset()         { *m = PreacceptRequest{} }
func (m *PreacceptRequest) String() string { return proto.CompactTextString(m) }
func (*PreacceptRequest) ProtoMessage()    {}
func (*PreacceptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{1}
}

func (m *PreacceptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreacceptRequest.Unmarshal(m, b)
}
func (m *PreacceptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreacceptRequest.Marshal(b, m, deterministic)
}
func (m *PreacceptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreacceptRequest.Merge(m, src)
}
func (m *PreacceptRequest) XXX_Size() int {
	return xxx_messageInfo_PreacceptRequest.Size(m)
}
func (m *PreacceptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PreacceptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PreacceptRequest proto.InternalMessageInfo

func (m *PreacceptRequest) GetInst() *Instance {
	if m != nil {
		return m.Inst
	}
	return nil
}

type PreacceptReply struct {
	Seq                  int64    `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Slot                 int64    `protobuf:"varint,2,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Deps                 []int64  `protobuf:"varint,3,rep,packed,name=Deps,proto3" json:"Deps,omitempty"`
	Changed              bool     `protobuf:"varint,4,opt,name=Changed,proto3" json:"Changed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreacceptReply) Reset()         { *m = PreacceptReply{} }
func (m *PreacceptReply) String() string { return proto.CompactTextString(m) }
func (*PreacceptReply) ProtoMessage()    {}
func (*PreacceptReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{2}
}

func (m *PreacceptReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreacceptReply.Unmarshal(m, b)
}
func (m *PreacceptReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreacceptReply.Marshal(b, m, deterministic)
}
func (m *PreacceptReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreacceptReply.Merge(m, src)
}
func (m *PreacceptReply) XXX_Size() int {
	return xxx_messageInfo_PreacceptReply.Size(m)
}
func (m *PreacceptReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PreacceptReply.DiscardUnknown(m)
}

var xxx_messageInfo_PreacceptReply proto.InternalMessageInfo

func (m *PreacceptReply) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PreacceptReply) GetSlot() int64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *PreacceptReply) GetDeps() []int64 {
	if m != nil {
		return m.Deps
	}
	return nil
}

func (m *PreacceptReply) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

type AcceptRequest struct {
	Inst                 *Instance `protobuf:"bytes,1,opt,name=Inst,proto3" json:"Inst,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AcceptRequest) Reset()         { *m = AcceptRequest{} }
func (m *AcceptRequest) String() string { return proto.CompactTextString(m) }
func (*AcceptRequest) ProtoMessage()    {}
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{3}
}

func (m *AcceptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptRequest.Unmarshal(m, b)
}
func (m *AcceptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptRequest.Marshal(b, m, deterministic)
}
func (m *AcceptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptRequest.Merge(m, src)
}
func (m *AcceptRequest) XXX_Size() int {
	return xxx_messageInfo_AcceptRequest.Size(m)
}
func (m *AcceptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptRequest proto.InternalMessageInfo

func (m *AcceptRequest) GetInst() *Instance {
	if m != nil {
		return m.Inst
	}
	return nil
}

type AcceptReply struct {
	Slot                 int64    `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptReply) Reset()         { *m = AcceptReply{} }
func (m *AcceptReply) String() string { return proto.CompactTextString(m) }
func (*AcceptReply) ProtoMessage()    {}
func (*AcceptReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{4}
}

func (m *AcceptReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptReply.Unmarshal(m, b)
}
func (m *AcceptReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptReply.Marshal(b, m, deterministic)
}
func (m *AcceptReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptReply.Merge(m, src)
}
func (m *AcceptReply) XXX_Size() int {
	return xxx_messageInfo_AcceptReply.Size(m)
}
func (m *AcceptReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptReply.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptReply proto.InternalMessageInfo

func (m *AcceptReply) GetSlot() int64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

type CommitRequest struct {
	Inst                 *Instance `protobuf:"bytes,1,opt,name=Inst,proto3" json:"Inst,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{5}
}

func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (m *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(m, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetInst() *Instance {
	if m != nil {
		return m.Inst
	}
	return nil
}

type Instance struct {
	Rep                  int64        `protobuf:"varint,1,opt,name=Rep,proto3" json:"Rep,omitempty"`
	Slot                 int64        `protobuf:"varint,2,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Seq                  int64        `protobuf:"varint,5,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Deps                 []int64      `protobuf:"varint,6,rep,packed,name=Deps,proto3" json:"Deps,omitempty"`
	State                InstState    `protobuf:"varint,7,opt,name=State,proto3,enum=pb.InstState" json:"State,omitempty"`
	Acks                 int32        `protobuf:"varint,8,opt,name=Acks,proto3" json:"Acks,omitempty"`
	Changed              bool         `protobuf:"varint,9,opt,name=Changed,proto3" json:"Changed,omitempty"`
	Visited              int64        `protobuf:"varint,10,opt,name=Visited,proto3" json:"Visited,omitempty"`
	Ops                  []*Operation `protobuf:"bytes,11,rep,name=Ops,proto3" json:"Ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{6}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetRep() int64 {
	if m != nil {
		return m.Rep
	}
	return 0
}

func (m *Instance) GetSlot() int64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *Instance) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Instance) GetDeps() []int64 {
	if m != nil {
		return m.Deps
	}
	return nil
}

func (m *Instance) GetState() InstState {
	if m != nil {
		return m.State
	}
	return InstState_PREACCEPTED
}

func (m *Instance) GetAcks() int32 {
	if m != nil {
		return m.Acks
	}
	return 0
}

func (m *Instance) GetChanged() bool {
	if m != nil {
		return m.Changed
	}
	return false
}

func (m *Instance) GetVisited() int64 {
	if m != nil {
		return m.Visited
	}
	return 0
}

func (m *Instance) GetOps() []*Operation {
	if m != nil {
		return m.Ops
	}
	return nil
}

type Operation struct {
	Type                 AccessType `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.AccessType" json:"Type,omitempty"`
	Key                  string     `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte     `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Identity             string     `protobuf:"bytes,4,opt,name=Identity,proto3" json:"Identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{7}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetType() AccessType {
	if m != nil {
		return m.Type
	}
	return AccessType_ACCESS_WRITE
}

func (m *Operation) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Operation) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Operation) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type ProposeRequest struct {
	Op                   *Operation `protobuf:"bytes,1,opt,name=Op,proto3" json:"Op,omitempty"`
	Identity             string     `protobuf:"bytes,2,opt,name=Identity,proto3" json:"Identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProposeRequest) Reset()         { *m = ProposeRequest{} }
func (m *ProposeRequest) String() string { return proto.CompactTextString(m) }
func (*ProposeRequest) ProtoMessage()    {}
func (*ProposeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{8}
}

func (m *ProposeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposeRequest.Unmarshal(m, b)
}
func (m *ProposeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposeRequest.Marshal(b, m, deterministic)
}
func (m *ProposeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposeRequest.Merge(m, src)
}
func (m *ProposeRequest) XXX_Size() int {
	return xxx_messageInfo_ProposeRequest.Size(m)
}
func (m *ProposeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProposeRequest proto.InternalMessageInfo

func (m *ProposeRequest) GetOp() *Operation {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *ProposeRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type ProposeReply struct {
	Slot                 int64    `protobuf:"varint,1,opt,name=Slot,proto3" json:"Slot,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProposeReply) Reset()         { *m = ProposeReply{} }
func (m *ProposeReply) String() string { return proto.CompactTextString(m) }
func (*ProposeReply) ProtoMessage()    {}
func (*ProposeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{9}
}

func (m *ProposeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposeReply.Unmarshal(m, b)
}
func (m *ProposeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposeReply.Marshal(b, m, deterministic)
}
func (m *ProposeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposeReply.Merge(m, src)
}
func (m *ProposeReply) XXX_Size() int {
	return xxx_messageInfo_ProposeReply.Size(m)
}
func (m *ProposeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposeReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProposeReply proto.InternalMessageInfo

func (m *ProposeReply) GetSlot() int64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *ProposeReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type WriteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{10}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WriteRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type WriteReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteReply) Reset()         { *m = WriteReply{} }
func (m *WriteReply) String() string { return proto.CompactTextString(m) }
func (*WriteReply) ProtoMessage()    {}
func (*WriteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{11}
}

func (m *WriteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteReply.Unmarshal(m, b)
}
func (m *WriteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteReply.Marshal(b, m, deterministic)
}
func (m *WriteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteReply.Merge(m, src)
}
func (m *WriteReply) XXX_Size() int {
	return xxx_messageInfo_WriteReply.Size(m)
}
func (m *WriteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteReply.DiscardUnknown(m)
}

var xxx_messageInfo_WriteReply proto.InternalMessageInfo

type WriteReadRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteReadRequest) Reset()         { *m = WriteReadRequest{} }
func (m *WriteReadRequest) String() string { return proto.CompactTextString(m) }
func (*WriteReadRequest) ProtoMessage()    {}
func (*WriteReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{12}
}

func (m *WriteReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteReadRequest.Unmarshal(m, b)
}
func (m *WriteReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteReadRequest.Marshal(b, m, deterministic)
}
func (m *WriteReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteReadRequest.Merge(m, src)
}
func (m *WriteReadRequest) XXX_Size() int {
	return xxx_messageInfo_WriteReadRequest.Size(m)
}
func (m *WriteReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteReadRequest proto.InternalMessageInfo

func (m *WriteReadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WriteReadRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type WriteReadReply struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteReadReply) Reset()         { *m = WriteReadReply{} }
func (m *WriteReadReply) String() string { return proto.CompactTextString(m) }
func (*WriteReadReply) ProtoMessage()    {}
func (*WriteReadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{13}
}

func (m *WriteReadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteReadReply.Unmarshal(m, b)
}
func (m *WriteReadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteReadReply.Marshal(b, m, deterministic)
}
func (m *WriteReadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteReadReply.Merge(m, src)
}
func (m *WriteReadReply) XXX_Size() int {
	return xxx_messageInfo_WriteReadReply.Size(m)
}
func (m *WriteReadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteReadReply.DiscardUnknown(m)
}

var xxx_messageInfo_WriteReadReply proto.InternalMessageInfo

func (m *WriteReadReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WriteReadReply) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ReadRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{14}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReadRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ReadReply struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReply) Reset()         { *m = ReadReply{} }
func (m *ReadReply) String() string { return proto.CompactTextString(m) }
func (*ReadReply) ProtoMessage()    {}
func (*ReadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d45c80f8c19d36, []int{15}
}

func (m *ReadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReply.Unmarshal(m, b)
}
func (m *ReadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReply.Marshal(b, m, deterministic)
}
func (m *ReadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReply.Merge(m, src)
}
func (m *ReadReply) XXX_Size() int {
	return xxx_messageInfo_ReadReply.Size(m)
}
func (m *ReadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReply proto.InternalMessageInfo

func (m *ReadReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReadReply) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("pb.InstState", InstState_name, InstState_value)
	proto.RegisterEnum("pb.AccessType", AccessType_name, AccessType_value)
	proto.RegisterType((*PeerRequest)(nil), "pb.PeerRequest")
	proto.RegisterType((*PreacceptRequest)(nil), "pb.PreacceptRequest")
	proto.RegisterType((*PreacceptReply)(nil), "pb.PreacceptReply")
	proto.RegisterType((*AcceptRequest)(nil), "pb.AcceptRequest")
	proto.RegisterType((*AcceptReply)(nil), "pb.AcceptReply")
	proto.RegisterType((*CommitRequest)(nil), "pb.CommitRequest")
	proto.RegisterType((*Instance)(nil), "pb.Instance")
	proto.RegisterType((*Operation)(nil), "pb.Operation")
	proto.RegisterType((*ProposeRequest)(nil), "pb.ProposeRequest")
	proto.RegisterType((*ProposeReply)(nil), "pb.ProposeReply")
	proto.RegisterType((*WriteRequest)(nil), "pb.WriteRequest")
	proto.RegisterType((*WriteReply)(nil), "pb.WriteReply")
	proto.RegisterType((*WriteReadRequest)(nil), "pb.WriteReadRequest")
	proto.RegisterType((*WriteReadReply)(nil), "pb.WriteReadReply")
	proto.RegisterType((*ReadRequest)(nil), "pb.ReadRequest")
	proto.RegisterType((*ReadReply)(nil), "pb.ReadReply")
}

func init() { proto.RegisterFile("comm.proto", fileDescriptor_84d45c80f8c19d36) }

var fileDescriptor_84d45c80f8c19d36 = []byte{
	// 764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0xce, 0xda, 0xf9, 0xf3, 0xd8, 0x09, 0x7b, 0x56, 0x5c, 0x58, 0x48, 0x47, 0xf8, 0xf8, 0xdc,
	0x58, 0x1c, 0x09, 0x1d, 0x02, 0xad, 0x50, 0xd5, 0x9b, 0x34, 0x71, 0x45, 0x04, 0x34, 0xd1, 0x3a,
	0xfc, 0xf4, 0x0a, 0x99, 0x64, 0x05, 0x56, 0x93, 0x78, 0x89, 0xcd, 0x45, 0x6e, 0xfb, 0x84, 0x7d,
	0x88, 0x3e, 0x48, 0xb5, 0xeb, 0x9f, 0xd8, 0x16, 0x95, 0xa0, 0x77, 0xfb, 0xcd, 0xcc, 0x37, 0xdf,
	0xcc, 0xec, 0xac, 0x0d, 0x30, 0x0b, 0x97, 0xcb, 0x43, 0xbe, 0x0e, 0xe3, 0x90, 0x28, 0xfc, 0xde,
	0xfe, 0xa1, 0x80, 0x3e, 0x61, 0x6c, 0x4d, 0xd9, 0xd3, 0x33, 0x8b, 0x62, 0xb2, 0x0f, 0xf5, 0xe9,
	0x86, 0x33, 0x13, 0x59, 0xc8, 0xe9, 0xf6, 0xf4, 0x43, 0x7e, 0x7f, 0x78, 0x19, 0x3d, 0x08, 0x13,
	0x95, 0x0e, 0x42, 0xa0, 0xfe, 0x79, 0x1d, 0x2e, 0x4d, 0xc5, 0x42, 0x8e, 0x4a, 0xe5, 0x99, 0x9c,
	0x80, 0xc6, 0xd7, 0xcc, 0x9f, 0xcd, 0x18, 0x8f, 0x4d, 0xb0, 0x90, 0xa3, 0xf7, 0x76, 0x05, 0x73,
	0x92, 0x19, 0xd3, 0xec, 0x67, 0x35, 0xba, 0x0d, 0x24, 0x1f, 0xa1, 0x9b, 0x83, 0x35, 0xe3, 0x8b,
	0x8d, 0xa9, 0x4b, 0x2a, 0xa9, 0x50, 0xf9, 0x62, 0x73, 0x56, 0xa3, 0x95, 0x58, 0xf2, 0x1f, 0x34,
	0x53, 0x41, 0x43, 0xb2, 0xfe, 0x12, 0xac, 0x7e, 0x45, 0x2d, 0x0d, 0x21, 0xc7, 0xa0, 0x17, 0x75,
	0x3a, 0x92, 0xb1, 0x53, 0x64, 0x24, 0x22, 0x7a, 0x45, 0x41, 0x0c, 0x2b, 0x88, 0xcd, 0xee, 0x56,
	0x61, 0x20, 0x2d, 0x05, 0x85, 0x24, 0xe4, 0x93, 0x06, 0xad, 0x25, 0x8b, 0x22, 0xff, 0x81, 0xd9,
	0x27, 0x80, 0xab, 0x8d, 0x13, 0x0b, 0xea, 0xa3, 0x55, 0x14, 0xcb, 0xb1, 0xea, 0x3d, 0x43, 0x64,
	0x12, 0xd8, 0x5f, 0xcd, 0x18, 0x95, 0x1e, 0x7b, 0x0e, 0xdd, 0x72, 0xcf, 0x04, 0x83, 0xea, 0xb1,
	0x27, 0x49, 0x51, 0xa9, 0x38, 0x8a, 0xd9, 0x7b, 0x8b, 0x30, 0xce, 0x66, 0x2f, 0xce, 0xc2, 0x36,
	0x64, 0x3c, 0x32, 0x55, 0x4b, 0x15, 0x36, 0x71, 0x26, 0x26, 0xb4, 0x06, 0x8f, 0xfe, 0xea, 0x81,
	0xcd, 0xcd, 0xba, 0x85, 0x9c, 0x36, 0xcd, 0xa0, 0x7d, 0x04, 0x9d, 0xfe, 0x1b, 0x0b, 0xfb, 0x07,
	0xf4, 0xc2, 0x90, 0xf2, 0x1a, 0xd0, 0xb6, 0x06, 0x91, 0xb5, 0x34, 0x97, 0x57, 0x64, 0xfd, 0x89,
	0xa0, 0x9d, 0x99, 0x44, 0xa7, 0x94, 0xf1, 0xac, 0x53, 0xca, 0xf8, 0x8b, 0x9d, 0xa6, 0xf3, 0x68,
	0x94, 0xe6, 0x21, 0x7b, 0x6f, 0x16, 0x7a, 0xff, 0x17, 0x1a, 0x5e, 0xec, 0xc7, 0xcc, 0x6c, 0xc9,
	0x0d, 0xee, 0x64, 0xda, 0xd2, 0x48, 0x13, 0x9f, 0x20, 0xf6, 0x67, 0xdf, 0x22, 0xb3, 0x6d, 0x21,
	0xa7, 0x41, 0xe5, 0xb9, 0x38, 0x34, 0xad, 0x34, 0x34, 0xe1, 0xb9, 0x0e, 0xa2, 0x20, 0x66, 0x73,
	0xb9, 0xdc, 0x2a, 0xcd, 0x20, 0xd9, 0x07, 0x75, 0xcc, 0x23, 0x53, 0xb7, 0x54, 0x47, 0x4f, 0xa4,
	0xc6, 0x9c, 0xad, 0xfd, 0x38, 0x08, 0x57, 0x54, 0x78, 0xec, 0x08, 0xb4, 0xdc, 0x42, 0xec, 0xd2,
	0xdb, 0xea, 0x66, 0xeb, 0x17, 0x45, 0x85, 0xe7, 0x85, 0x41, 0x3d, 0x67, 0x1b, 0xd9, 0xb7, 0x46,
	0xc5, 0x91, 0xec, 0x42, 0xe3, 0xda, 0x5f, 0x3c, 0x33, 0x53, 0xb5, 0x90, 0x63, 0xd0, 0x04, 0x90,
	0x3d, 0x68, 0x8f, 0xe6, 0x6c, 0x15, 0x07, 0xf1, 0x46, 0xde, 0xb1, 0x46, 0x73, 0x6c, 0x9f, 0x8b,
	0x55, 0x0a, 0x79, 0x18, 0xb1, 0xec, 0x3e, 0xfe, 0x06, 0x65, 0xcc, 0xd3, 0xdb, 0xa8, 0x94, 0xa9,
	0x8c, 0x79, 0x29, 0x99, 0x52, 0x49, 0x76, 0x0a, 0x46, 0x9e, 0xec, 0x37, 0xf7, 0xbf, 0x2d, 0x31,
	0x21, 0x27, 0xc0, 0x7e, 0x0f, 0xc6, 0xcd, 0x3a, 0x88, 0xf3, 0x22, 0xd2, 0xd6, 0xd0, 0x0b, 0xad,
	0x29, 0x85, 0xd6, 0x6c, 0x03, 0x20, 0xe5, 0xf1, 0xc5, 0xc6, 0xfe, 0x00, 0x38, 0x45, 0xfe, 0xfc,
	0xad, 0x99, 0x4e, 0xa1, 0x5b, 0xe0, 0xa6, 0x6f, 0xea, 0x55, 0xcc, 0x77, 0xa0, 0xff, 0x89, 0xe0,
	0x31, 0x68, 0x6f, 0xd6, 0x3a, 0xf8, 0x8e, 0xa0, 0x95, 0x7e, 0x63, 0x49, 0x07, 0xb4, 0x09, 0x75,
	0xfb, 0x83, 0x81, 0x3b, 0x99, 0xe2, 0x1a, 0x21, 0xd0, 0xcd, 0x21, 0x75, 0x27, 0x17, 0x5f, 0x31,
	0x22, 0x00, 0xcd, 0xd4, 0xaf, 0x90, 0x1d, 0xd0, 0x8b, 0x4e, 0x55, 0x38, 0x07, 0xe3, 0xcb, 0xcb,
	0xd1, 0x14, 0xd7, 0x85, 0x33, 0x39, 0x27, 0xce, 0x06, 0xd1, 0xa1, 0x35, 0xa1, 0xe3, 0xc9, 0xd8,
	0x73, 0x71, 0x53, 0x28, 0xb9, 0xb7, 0x99, 0xaf, 0x7d, 0x70, 0x0a, 0x5a, 0xfe, 0x4a, 0x04, 0x33,
	0x97, 0x75, 0x87, 0xb8, 0x46, 0x0c, 0x68, 0xe7, 0x48, 0x11, 0xc8, 0xbd, 0x75, 0x07, 0x57, 0x02,
	0xa9, 0x07, 0xd7, 0x00, 0xdb, 0x2d, 0x26, 0x18, 0x0c, 0x11, 0xe9, 0x79, 0x77, 0x37, 0x74, 0x34,
	0x75, 0x71, 0x2d, 0xab, 0xd1, 0xf3, 0xee, 0xa8, 0xdb, 0x1f, 0x62, 0x44, 0x76, 0x01, 0x17, 0x43,
	0xa4, 0x55, 0x29, 0x84, 0x7d, 0xb9, 0xba, 0xb8, 0xc0, 0x6a, 0x8f, 0x43, 0x4b, 0xcc, 0x31, 0x98,
	0xf9, 0xe4, 0x08, 0x5a, 0xe9, 0x0e, 0x92, 0xf4, 0xe7, 0x50, 0xdc, 0xee, 0x3d, 0x5c, 0xb2, 0x89,
	0xa5, 0xa9, 0x91, 0x1e, 0xb4, 0x87, 0x41, 0xc4, 0xfd, 0x78, 0xf6, 0x48, 0xe4, 0x87, 0xbe, 0xf0,
	0x93, 0xdb, 0xab, 0x1a, 0xec, 0x9a, 0x83, 0xfe, 0x47, 0xf7, 0x4d, 0xf9, 0x5b, 0x3c, 0xfe, 0x15,
	0x00, 0x00, 0xff, 0xff, 0x0e, 0x2c, 0xc5, 0x78, 0x24, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReplicaClient is the client API for Replica service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicaClient interface {
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeReply, error)
	Dispatch(ctx context.Context, opts ...grpc.CallOption) (Replica_DispatchClient, error)
}

type replicaClient struct {
	cc *grpc.ClientConn
}

func NewReplicaClient(cc *grpc.ClientConn) ReplicaClient {
	return &replicaClient{cc}
}

func (c *replicaClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeReply, error) {
	out := new(ProposeReply)
	err := c.cc.Invoke(ctx, "/pb.Replica/Propose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaClient) Dispatch(ctx context.Context, opts ...grpc.CallOption) (Replica_DispatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Replica_serviceDesc.Streams[0], "/pb.Replica/Dispatch", opts...)
	if err != nil {
		return nil, err
	}
	x := &replicaDispatchClient{stream}
	return x, nil
}

type Replica_DispatchClient interface {
	Send(*PeerRequest) error
	Recv() (*PeerRequest, error)
	grpc.ClientStream
}

type replicaDispatchClient struct {
	grpc.ClientStream
}

func (x *replicaDispatchClient) Send(m *PeerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *replicaDispatchClient) Recv() (*PeerRequest, error) {
	m := new(PeerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReplicaServer is the server API for Replica service.
type ReplicaServer interface {
	Propose(context.Context, *ProposeRequest) (*ProposeReply, error)
	Dispatch(Replica_DispatchServer) error
}

func RegisterReplicaServer(s *grpc.Server, srv ReplicaServer) {
	s.RegisterService(&_Replica_serviceDesc, srv)
}

func _Replica_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Replica/Propose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Replica_Dispatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplicaServer).Dispatch(&replicaDispatchServer{stream})
}

type Replica_DispatchServer interface {
	Send(*PeerRequest) error
	Recv() (*PeerRequest, error)
	grpc.ServerStream
}

type replicaDispatchServer struct {
	grpc.ServerStream
}

func (x *replicaDispatchServer) Send(m *PeerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *replicaDispatchServer) Recv() (*PeerRequest, error) {
	m := new(PeerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Replica_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Replica",
	HandlerType: (*ReplicaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propose",
			Handler:    _Replica_Propose_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dispatch",
			Handler:       _Replica_Dispatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "comm.proto",
}
